def create_advotes():
    adv17 = "Avery Bradley, Boston, 46 (12); Klay Thompson, Golden State, 45 (16); John Wall, Washington, 38 (14); DeAndre Jordan, LA Clippers, 35 (1); Paul Millsap, Atlanta, 35; Hassan Whiteside, Miami, 25 (1); Marcus Smart, Boston, 21 (5); Jimmy Butler, Chicago, 18; LeBron James, Cleveland, 12 (1); Robert Covington, Philadelphia, 11 (2); Russell Westbrook, Oklahoma City, 10 (5); Paul George, Indiana, 7; Kevin Durant, Golden State, 6; Dwight Howard, Atlanta, 6 (1); Mike Conley, Memphis, 5 (1); Jae Crowder, Boston, 5; Jrue Holiday, New Orleans, 5; Wesley Matthews, Dallas, 4 (2); Stephen Curry, Golden State, 3; Andre Iguodala, Golden State, 3 (1); Michael Kidd-Gilchrist, Charlotte, 3; Ricky Rubio, Minnesota, 3; P.J. Tucker, Toronto, 3; Trevor Ariza, Houston, 2; Nicolas Batum, Charlotte, 2; Marc Gasol, Memphis, 2; Eric Gordon, Houston, 2 (1); Karl-Anthony Towns, Minnesota, 2 (1); Steven Adams, Oklahoma City, 1; LaMarcus Aldridge, San Antonio, 1; Al-Farouq Aminu, Portland, 1; Kentavious Caldwell-Pope, Detroit, 1; George Hill, Utah, 1; Serge Ibaka, Toronto, 1; Damian Lillard, Portland, 1; Luc Mbah a Moute, LA Clippers, 1; Austin Rivers, LA Clippers, 1; Isaiah Thomas, Boston, 1; Cody Zeller, Charlotte, 1"

    adv16 = "Rudy Gobert, Utah, 64 (17); Klay Thompson, Golden State, 49 (16); Jae Crowder, Boston, 47 (3); LeBron James, Cleveland, 43 (5); Kyle Lowry, Toronto, 43 (9); Danny Green, San Antonio, 39 (9); Russell Westbrook, Oklahoma City, 35 (12); Tim Duncan, San Antonio, 33 (5); Ricky Rubio, Minnesota, 30 (6); Kentavious Caldwell-Pope, Detroit, 27 (3); Anthony Davis, New Orleans, 24 (3); Andre Drummond, Detroit, 14 (5); Serge Ibaka, Oklahoma City, 14 (1); Stephen Curry, Golden State, 13 (3); Andre Iguodala, Golden State, 13 (3); Patrick Beverley, Houston, 11 (1); Al Horford, Atlanta, 7 (1); Marcus Smart, Boston, 7 (2); John Wall, Washington, 6; Giannis Antetokounmpo, Milwaukee, 3; Trevor Ariza, Houston, 3; Kent Bazemore, Atlanta, 3; Andrew Bogut, Golden State, 3 (1); DeMarcus Cousins, Sacramento, 3 (1); Nicolas Batum, Charlotte, 2; Victor Oladipo, Orlando, 2 (1); LaMarcus Aldridge, San Antonio, 1; Harrison Barnes, Golden State, 1; Bismack Biyombo, Toronto, 1; Mike Conley, Memphis, 1; Kevin Durant, Oklahoma City, 1; Derrick Favors, Utah, 1; George Hill, Indiana, 1; Wesley Matthews, Dallas, 1; Luc Mbah a Moute, Los Angeles Clippers, 1; Kristaps Porzingis, New York, 1; Andre Roberson, Oklahoma City, 1; Mike Scott, Atlanta, 1; Dwyane Wade, Miami, 1"

    adv15 = "Rudy Gobert, Utah, 54 (5); LeBron James, Cleveland, 47 (6); Russell Westbrook, Oklahoma City, 35 (13); Avery Bradley, Boston, 26 (5); Michael Kidd-Gilchrist, Charlotte, 21 (2), Klay Thompson, Golden State, 19 (3); Marc Gasol, Memphis, 18 (2); Danny Green, San Antonio, 18; Trevor Ariza, Houston, 17 (1); Stephen Curry, Golden State, 14 (2); DeMarre Carroll, Atlanta, 11 (1); Patrick Beverley, Houston, 10 (1); Khris Middleton, Milwaukee, 9 (1); Serge Ibaka, Oklahoma City, 8; Andre Iguodala, Golden State, 8; Paul Millsap, Atlanta, 8; Jeff Teague, Atlanta, 7 (1); Mike Conley, Memphis, 6 (2); Joakim Noah, Chicago, 6; Nerlens Noel, Philadelphia, 5 (1); P.J. Tucker, Phoenix, 4; Giannis Antetokounmpo, Milwaukee, 3; Pau Gasol, Chicago, 3; Wesley Matthews, Portland, 3; James Harden, Houston, 2; Marcus Smart, Boston, 2; Hassan Whiteside, Miami, 2 (1); Eric Bledsoe, Phoenix, 1; DeMarcus Cousins, Sacramento, 1; Andre Drummond, Detroit, 1; Manu Ginobili, San Antonio, 1; Blake Griffin, L.A. Clippers, 1; George Hill, Indiana, 1; Al Horford, Atlanta, 1; Victor Oladipo, Orlando, 1; Zaza Pachulia, Milwaukee, 1; Elfrid Payton, Orlando, 1; Zach Randolph, Memphis, 1; Rajon Rondo, Dallas, 1; Iman Shumpert, Cleveland, 1; Dwyane Wade, Miami, 1"

    adv14 = "DeAndre Jordan, L.A. Clippers, 63 (14); Anthony Davis, New Orleans, 62 (18); Tony Allen, Memphis, 60 (17); Tim Duncan, San Antonio, 45 (12); Dwight Howard, Houston, 26 (6); Taj Gibson, Chicago, 21 (2); Mike Conley, Memphis, 21 (5); Ricky Rubio, Minnesota, 19 (5); Lance Stephenson, Indiana, 14 (3); P.J. Tucker, Phoenix, 13 (2); Kevin Durant, Oklahoma City, 10 (2); Kyle Lowry, Toronto, 10 (3); Eric Bledsoe, Phoenix, 9 (1); Marc Gasol, Memphis, 8; John Wall, Washington, 8 (1); Thabo Sefolosha, Oklahoma City, 8 (1); Kirk Hinrich, Chicago, 7 (2); Trevor Ariza, Washington, 5 (2); Avery Bradley, Boston, 5 (1); Russell Westbrook, Oklahoma City, 5 (1); Klay Thompson, Golden State, 5; Andrew Bogut, Golden State, 4; Chris Bosh, Miami, 4 (1); Luol Deng, Cleveland, 4 (1); Wesley Matthews, Portland, 4 (1); Tony Parker, San Antonio, 4 (1); Nicolas Batum, Portland, 3 (1); Stephen Curry, Golden State, 3 (1); Danny Green, San Antonio, 3 (1); Michael Kidd-Gilchrist, Charlotte, 3; Shaun Livingston, Brooklyn, 3 (1); Victor Oladipo, Orlando, 3 (1); DeMarre Carroll, Atlanta, 2; Matt Barnes, L.A. Clippers, 2 (1); James Harden, Houston, 2; George Hill, Indiana, 2; Jeff Teague, Atlanta, 2; Dwyane Wade, Miami, 2 (1); Kemba Walker, Charlotte, 2; David West, Indiana, 2; Arron Afflalo, Orlando, 1; Corey Brewer, Minnesota, 1; Michael Carter-Williams, Philadelphia, 1; Darren Collison, L.A. Clippers, 1; DeMar DeRozan, Toronto, 1; Andre Drummond, Detroit, 1; Monta Ellis, Dallas, 1; Danny Granger, L.A. Clippers, 1; Draymond Green, Golden State, 1; Reggie Jackson, Oklahoma City, 1; David Lee, Golden State, 1; Paul Millsap, Atlanta, 1; Rajon Rondo, Boston, 1"

    adv13 = "Andre Iguodala, Denver, 16 (2); Larry Sanders, Milwaukee, 16 (4); Thabo Sefolosha, Oklahoma City, 15 (2); Luol Deng, Chicago, 11 (1); Dwight Howard, L.A. Lakers, 9 (3); Kobe Bryant, L.A. Lakers, 6 (1); Roy Hibbert, Indiana, 6 (2); Kenneth Faried, Denver, 4 (1); Russell Westbrook, Oklahoma City, 4 (1); Shane Battier, Miami, 2; Nicolas Batum, Portland, 2 (1); Corey Brewer, Denver, 2; George Hill, Indiana, 2; Mike James, Dallas, 2 (1); Kawhi Leonard, San Antonio, 2, (1); Tony Parker, San Antonio, 2 (1); Dwyane Wade, Miami, 2; Metta World Peace, L.A. Lakers, 2 (1); Eric Bledsoe, L.A. Clippers, 1; Kevin Durant, Oklahoma City, 1; Jrue Holiday, Philadelphia, 1; Andrei Kirilenko, Minnesota, 1; Iman Shumpert, New York, 1; David West, Indiana, 1"

    adv12 = "Andre Iguodala, Philadelphia, 19 (4); Joakim Noah, Chicago, 14; Iman Shumpert, New York, 13 (4); Paul George, Indiana, 10 (2); Russell Westbrook, Oklahoma City, 9 (2); Josh Smith, Atlanta, 8 (2); Dwyane Wade, Miami, 5 (1); Thabo Sefolosha, Oklahoma City, 5 (1); Grant Hill, Phoenix, 5 (1); Tim Duncan, San Antonio, 5 (1); Avery Bradley, Boston, 3 (1); Marc Gasol, Memphis, 3 (1); Metta World Peace, L.A. Lakers, 3; Shawn Marion, Dallas, 3; Joe Johnson, Atlanta, 2, (1); Mike Conley, Memphis, 2; Derrick Rose, Chicago, 1; Jrue Holiday, Philadelphia, 1; Carlos Boozer, Chicago, 1; Luc Mbah a Moute, Milwaukee, 1"

    adv11 = "Derrick Rose, Chicago, 14 (4); Dwyane Wade, Miami, 13 (3); Russell Westbrook, Oklahoma City, 13 (4); Gerald Wallace, Portland, 11 (1); Grant Hill, Phoenix, 11 (4); Luol Deng, Chicago, 11 (4); Tim Duncan, San Antonio, 11 (3); Chuck Hayes, Houston, 10 (2); Al Horford, Atlanta, 7 (3); Josh Smith, Atlanta, 7 (1); Ron Artest, Los Angeles Lakers, 7 (1); Serge Ibaka, Oklahoma City, 6 (1); Shane Battier, Memphis, 5 (2); Thabo Sefolosha, Oklahoma City, 5; Wesley Matthews, Portland, 4 (2); Kendrick Perkins, Oklahoma City, 3; Nicolas Batum, Portland, 3, (1); Joe Johnson, Atlanta, 2 (1); Keith Bogans, Chicago, 2 (1); Kyle Lowry, Houston, 2; Lamar Odom, Los Angeles Lakers, 2; Luc Mbah a Moute, Milwaukee, 2; Manu Ginobili, San Antonio, 2 (1); Andrew Bogut, Milwaukee, 1; Andrew Bynum, Los Angeles Lakers, 1; Arron Afflalo, Denver, 1; Jrue Holiday, Philadelphia, 1; Kirk Hinrich, Atlanta, 1; Nene Hilario, Denver, 1; Ronnie Brewer, Chicago, 1; Shawn Marion, Dallas, 1; Tayshaun Prince, Detroit, 1"

    adv10 = "Jason Kidd, Dallas, 12 (4); Marcus Camby, Portland, 12 (1); Ron Artest, Los Angeles, 11, (3); Deron Williams, Utah, 10, (2); Kirk Hinrich, Chicago, 9 (1); Andrew Bogut, Milwaukee, 8; Luc Mbah a Moute, Milwaukee, 8 (1); Arron Afflalo, Denver, 6 (1); Kenyon Martin, Denver, 5 (1); Kevin Garnett, Boston, 5 (1); Grant Hill, Phoenix, 4 (2); Joakim Noah, Chicago, 4; Kendrick Perkins, Boston, 4 (1); Shane Battier, Houston, 4 (1); Andrei Kirilenko, Utah, 3 (1); Russell Westbrook, Oklahoma City, 3; Trevor Ariza, Houston, 3 (1); Andre Iguodala, Philadelphia, 2; George Hill, San Antonio, 2 (1); Jermaine O’Neal, Miami, 2 (1); Joe Johnson, Atlanta, 2 (1); Lamar Odom, L.A. Lakers, 2 (1); Luis Scola, Houston, 2; Manu Ginobili, San Antonio, 2 (1); Nicolas Batum, Portland, 2; Caron Butler, Dallas, 1; Chauncey Billups, Denver, 1; Jared Dudley, Phoenix, 1; Kevin Durant, Oklahoma City, 1; Raymond Felton, Charlotte, 1; Marc Gasol, Memphis, 1; Pau Gasol, L.A. Lakers, 1; Chuck Hayes, Houston, 1; Brendan Haywood, Dallas, 1; Al Horford, Atlanta, 1; Serge Ibaka, Oklahoma City, 1; Ersan Ilyasova, Milwaukee, 1; Stephen Jackson, Charlotte, 1; Nene Hilario, Denver, 1; Chris Paul, New Orleans, 1; Tayshaun Prince, Detroit, 1; Earl Watson, Indiana, 1"

    adv09 = "Tayshaun Prince, Detroit, 15 (3); Raja Bell, Charlotte, 8 (2); Joel Przybilla, Portland, 7 (1); Chauncey Billups, Denver, 5; Ronnie Brewer, Utah, 5 (1); Andre Iguodala, Philadelphia, 5; Yao Ming, Houston, 5; Emeka Okafor, Charlotte, 5 (1); Kendrick Perkins, Boston, 4 (1); Samuel Dalembert, Philadelphia, 3; Derek Fisher, L.A. Lakers, 3 (1); Udonis Haslem, Miami, 3; Jason Kidd, Dallas, 3 (1); Anderson Varejao, Cleveland, 3; Deron Williams, Utah, 3; Trevor Ariza, L.A. Lakers, 2; Kirk Hinrich, Chicago, 2; Joe Johnson, Atlanta, 2 (1); Andrei Kirilenko, Utah, 2 (1); David Lee, New York, 2 (1); James Posey, New Orleans, 2; J.R. Smith, Denver, 2 (1); Gerald Wallace, Charlotte, 2; Nene Hilario, Denver, 1; Chris Andersen, Denver, 1; Pau Gasol, L.A. Lakers, 1; Antonio McDyess, Detroit, 1; Andre Miller, Philadelphia, 1; Travis Outlaw, Portland, 1; Brandon Roy, Portland, 1; Rasheed Wallace, Detroit, 1"

    adv08 = "Chauncey Billups, Detroit, 14 (5); Jason Kidd, Dallas, 13 (4); Rasheed Wallace, Detroit, 13 (3); Rajon Rondo, Boston, 11 (3); Deron Williams, Utah, 8, (3); Josh Smith, Atlanta, 8, (3); Ron Artest, Sacramento, 8 (2); Tyson Chandler, New Orleans, 8 (1); Andrei Kirilenko, Utah, 6; Derek Fisher, Los Angeles Lakers, 4 (1); LeBron James, Cleveland, 4 (1); Manu Ginobili, San Antonio, 4 (1); Kirk Hinrich, Chicago, 3 (1); Samuel Dalembert, Philadelphia, 3 (1); Andre Iguodala, Philadelphia, 2 (1); Brandon Roy, Portland, 2; Paul Pierce, Boston, 2; Andre Miller, Philadelphia, 1; Andres Nocioni, Chicago, 1; Baron Davis, Golden State, 1; Caron Butler, Washington, 1; Chris Bosh, Toronto, 1; Dikembe Mutombo, Houston, 1; Josh Howard, Dallas, 1; Richard Hamilton, Detroit, 1; Ronnie Brewer, Utah, 1"

    adv07 = "Shane Battier, Houston, 17 (6); Shawn Marion, Phoenix, 15 (5); Chauncey Billups, Detroit, 13 (5); Ron Artest, Sacramento, 12 (4); Gerald Wallace, Charlotte, 11 (2); Alonzo Mourning, Miami, 9 (4); Devin Harris, Dallas, 8 (2); Tyson Chandler, New Orleans/Oklahoma City, 8 (2); Josh Howard, Dallas, 7; Emeka Okafor, Charlotte, 6 (1); Luol Deng, Chicago, 5 (2); Rasheed Wallace, Detroit, 5 (1); Dwight Howard, Orlando, 5 (1); Andrei Kirilenko, Utah, 5; Josh Smith, Atlanta, 4 (1); Manu Ginobili, San Antonio, 4 (1); Richard Hamilton, Detroit, 3 (1); Jermaine O’Neal, Indiana, 3 (1); Andre Iguodala, Philadelphia, 3; Deron Williams, Utah, 3; Elton Brand, L.A. Clippers, 2 (1); Dwyane Wade, Miami, 2; Trenton Hassell, Minnesota, 2 (1); Tony Parker, San Antonio, 2; Caron Butler, Washington, 2; Chris Duhon, Chicago, 1; Allen Iverson, Denver, 1; Udonis Haslem, Miami, 1; Richard Jefferson, New Jersey, 1; Chris Paul, New Orleans/Oklahoma City, 1; Andre Miller, Philadelphia, 1; Joel Przybilla, Portland, 1; Francisco Elson, San Antonio, 1; Chris Bosh, Toronto, 1; Gilbert Arenas, Washington, 1"

    adv06 = "Rasheed Wallace, Detroit, 12 (3); Gerald Wallace, Charlotte, 11 (3); Shawn Marion, Phoenix, 11 (1); Raja Bell, Phoenix, 9 (2); Dwyane Wade, Miami, 8 (3); Kirk Hinrich, Chicago, 7 (3); Alonzo Mourning, Miami, 7 (1); Shane Battier, Memphis, 6 (1); Gilbert Arenas, Washington, 4 (1); Andre Iguodala, Philadelphia, 4; P.J. Brown, New Orleans/Okla. City, 3; Manu Ginobili, San Antonio, 3; Dwight Howard, Orlando, 3; Josh Howard, Dallas, 3 (1); Brevin Knight, Charlotte, 3; Shaquille O’Neal, Miami, 3 (1); Elton Brand, L.A. Clippers, 2 (1); LeBron James, Cleveland, 2 (1); Tony Parker, San Antonio, 2 (1); Quinton Ross, L.A. Clippers, 2 (1); Allen Iverson, Philadelphia, 2; Eddie Jones, Memphis, 2; Jason Collins, New Jersey, 1; Boris Diaw, Phoenix, 1; Pau Gasol, Memphis, 1; Trenton Hassel, Minnesota, 1; Mike James, Toronto, 1; Richard Jefferson, New Jersey, 1; Ruben Patterson, Denver, 1; Chris Paul, New Orleans/Okla. City, 1; Jason Terry, Dallas, 1; Yao Ming, Houston, 1"

    adv05 = "Shaquille O’Neal, Miami, 16 (3); Allen Iverson, Philadelphia, 14 (6); Kobe Bryant, Los Angeles Lakers, 12 (3); Shawn Marion, Phoenix, 9 (4); Manu Ginobili, San Antonio, 9; Rasheed Wallace, Detroit, 8 (1); Kenyon Martin, Denver, 6; Tony Parker, San Antonio, 5 (2); Andre Iguodala, Philadelphia, 5 (2); Shane Battier, Memphis, 4; Andre Miller, Denver, 4 (1); Tyson Chandler, Chicago, 3; Trenton Hassell, Minnesota, 3 (1); Kirk Hinrich, Chicago, 3; Joe Johnson, Phoenix, 3; Earl Watson, Memphis, 3 (1); Udonis Haslem, Miami, 2; Tracy McGrady, Houston, 2; Josh Howard, Dallas, 2 (1); Joel Przybilla, Portland, 2; Desmond Mason, Milwaukee, 2; Brevin Knight, Charlotte, 2; Vince Carter, New Jersey, 1; P.J. Brown, New Orleans, 1; Mickael Pietrus, Golden State, 1; Kurt Thomas, New York, 1; Jeff Foster, Indiana, 1; Greg Buckner, Denver, 1; Gilbert Arenas, Washington, 1; Gary Payton, Boston, 1; Emeka Okafor, Charlotte, 1; Eddie Jones, Miami, 1; Clifford Robinson, New Jersey, 1; Brendan Haywood, Washington, 1; Anthony Johnson, Indiana, 1; Andres Nocioni, Chicago, 1; Amaré Stoudemire, Phoenix, 1"

    advotes = [adv17, adv16, adv15, adv14, adv13, adv12, adv11, adv10, adv09, adv08, adv07, adv06, adv05]
    
    return advotes